# roles/replicator/tasks/main.yml
---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Create the 'openio' group
  group:
    name: openio
    gid: "{{ openio_group_openio_gid | default('220')}}"
  tags: install

- name: Create the 'openio' user
  user:
    name: openio
    comment: "openio account"
    uid: "{{ openio_user_openio_uid | default('120')}}"
    group: openio
  tags: install

- name: "Include {{ ansible_distribution }} tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Test directories presence
  stat:
    path: "{{ item }}"
  register: _dir
  with_items:
    - "/etc/gridinit.d/{{ openio_replicator_namespace }}"
    - "{{ openio_replicator_sysconfig_dir }}/replicator-{{ openio_replicator_serviceid }}"
    #- "{{ openio_replicator_volume }}"

- name: Ensure directories exists
  file:
    path: "{{ item.item }}"
    state: directory
    owner: openio
    group: openio
    mode: 0755
    recurse: true
  with_items: "{{ _dir.results }}"
  when: not item.stat.exists
  tags: install

- name: Ensure log directory
  file:
    path: "/var/log/oio/sds/{{ openio_replicator_namespace }}/replicator-{{ openio_replicator_serviceid }}"
    state: directory
    owner: "{{ syslog_user }}"
    group: openio
    mode: 0750
    recurse: true
  tags: install

- name: Generate configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: openio
    group: openio
    mode: 0644
  with_items:
    - src: "replicator.conf.j2"
      dest: "{{ openio_replicator_sysconfig_dir }}/\
        replicator-{{ openio_replicator_serviceid }}/replicator.conf"
    - src: "gridinit_replicator.conf.j2"
      dest: "{{ openio_replicator_gridinit_dir }}/{{ openio_replicator_gridinit_file_prefix }}\
        replicator-{{ openio_replicator_serviceid }}.conf"
  register: _replicator_conf

- name: restart replicator
  shell: |
    gridinit_cmd reload
    gridinit_cmd restart  {{openio_replicator_namespace}}-replicator-{{openio_replicator_serviceid}}
  when: 
    - _replicator_conf.changed
    - not openio_replicator_provision_only
  tags: configure
...
